# Site settings
title: Sara Fredman
email: sarafredman@gmail.com
url: https://sarafredman.github.io
description: "Sara Fredman is a writer and professor living in St. Louis. She holds a PhD in medieval English literature and is the nonfiction editor for december, a literary magazine. Her work has appeared in Longreads, Slate, The Rumpus, Tablet, and Lilith"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  primary-lighter: '#333333'
  links: '#219ab3'

# Footer settings
footer: Sara Fredman

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/sarafredman
  - title: Instagram
    url: https://www.instagram.com/sarafredman/

# Build settings
markdown: kramdown
permalink: pretty
