# Site settings
title: Sara Fredman
email: sarafredman@gmail.com
url: https://sarafredman.github.io
description: "Sara Fredman is a writer living in St. Louis. She holds a PhD in medieval English literature and her writing has appeared in The Washington Post, the Los Angeles Review of Books, the Times Literary Supplement, and other publications. She is the creator of <a href='https://sarafredman.substack.com'>Write Like a Mother</a>, a newsletter for writers who are also parents."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  primary-lighter: '#333333'
  links: '#219ab3'

# Footer settings
footer: Sara Fredman

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/sarafredman
  - title: Instagram
    url: https://www.instagram.com/sarafredman/
  - title: Substack
    url: https://sarafredman.substack.com

# Build settings
markdown: kramdown
permalink: pretty
